// order --- all user
export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAIL = "CREATE_ORDER_FAIL";

// orders --- all
export const USER_ORDER_REQUSET = "USER_ORDER_REQUSET";
export const USER_ORDER_SUCCESS = "USER_ORDER_SUCCESS";
export const USER_ORDER_FAIL = "USER_ORDER_FAIL";

// delete orders --- admin, seller, customer
export const DELETE_ORDER_REQUEST = "DELETE_ORDER_REQUEST";
export const DELETE_ORDER_SUCCESS = "DELETE_ORDER_SUCCESS";
export const DELETE_ORDER_FAIL = "DELETE_ORDER_FAIL";
export const DELETE_ORDER_RESET = "DELETE_ORDER_RESET";

// orders --- all
export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST";
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS";
export const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL";

// get seller orders --- seller
export const SELLER_ORDER_REQUEST = "SELLER_ORDER_REQUEST";
export const SELLER_ORDER_SUCCESS = "SELLER_ORDER_SUCCESS";
export const SELLER_ORDER_FAIL = "SELLER_ORDER_FAIL";

// get seller additional orders --- seller
export const SELLER_EXTRA_REQUEST = "SELLER_EXTRA_REQUEST";
export const SELLER_EXTRA_SUCCESS = "SELLER_EXTRA_SUCCESS";
export const SELLER_EXTRA_FAIL = "SELLER_EXTRA_FAIL";

// update orders --- seller
export const UPDATE_SELLER_ORDER_REQUEST = "UPDATE_SELLER_ORDER_REQUEST";
export const UPDATE_SELLER_ORDER_SUCCESS = "UPDATE_SELLER_ORDER_SUCCESS";
export const UPDATE_SELLER_ORDER_FAIL = "UPDATE_SELLER_ORDER_FAIL";
export const UPDATE_SELLER_ORDER_RESET = "UPDATE_SELLER_ORDER_RESET";

// get orders --- admin
export const ADMIN_ORDER_REQUEST = "ADMIN_ORDER_REQUEST";
export const ADMIN_ORDER_SUCCESS = "ADMIN_ORDER_SUCCESS";
export const ADMIN_ORDER_FAIL = "ADMIN_ORDER_FAIL";

// clear errors
export const CLEAR_ERRORS = "CLEAR_ERRORS";