// get home shops --- all user
export const HOME_PRODUCTS_REQUEST = "HOME_PRODUCTS_REQUEST";
export const HOME_PRODUCTS_SUCCESS = "HOME_PRODUCTS_SUCCESS";
export const HOME_PRODUCTS_FAIL = "HOME_PRODUCTS_FAIL";

// all products --- all user
export const ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST";
export const ALL_PRODUCT_SUCCESS = "ALL_PRODUCT_SUCCESS";
export const ALL_PRODUCT_FAIL = "ALL_PRODUCT_FAIL";

// get products by shop
export const PRODUCT_BY_SHOP_REQUEST = "PRODUCT_BY_SHOP_REQUEST";
export const PRODUCT_BY_SHOP_SUCCESS = "PRODUCT_BY_SHOP_SUCCESS";
export const PRODUCT_BY_SHOP_FAIL = "PRODUCT_BY_SHOP_FAIL";

// product details
export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";

// create product review --- all user
export const NEW_PRODUCT_REVIEW_REQUEST = "NEW_PRODUCT_REVIEW_REQUEST";
export const NEW_PRODUCT_REVIEW_SUCCESS = "NEW_PRODUCT_REVIEW_SUCCESS";
export const NEW_PRODUCT_REVIEW_FAIL = "NEW_PRODUCT_REVIEW_FAIL";
export const NEW_PRODUCT_REVIEW_RESET = "NEW_PRODUCT_REVIEW_RESET";

// delete shop review --- all user
export const DELETE_PRODUCT_REVIEW_REQUEST = "DELETE_PRODUCT_REVIEW_REQUEST";
export const DELETE_PRODUCT_REVIEW_SUCCESS = "DELETE_PRODUCT_REVIEW_SUCCESS";
export const DELETE_PRODUCT_REVIEW_FAIL = "DELETE_PRODUCT_REVIEW_FAIL";
export const DELETE_PRODUCT_REVIEW_RESET = "DELETE_PRODUCT_REVIEW_RESET";

// for creating products --- seller
export const CREATE_PRODUCT_REQUEST = "CREATE_PRODUCT_REQUEST";
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";
export const CREATE_PRODUCT_FAIL = "CREATE_PRODUCT_FAIL";
export const CREATE_PRODUCT_RESET = "CREATE_PRODUCT_RESET";

// seller products request --- seller
export const SELLER_PRODUCT_REQUEST = "SELLER_PRODUCT_REQUEST";
export const SELLER_PRODUCT_SUCCESS = "SELLER_PRODUCT_SUCCESS";
export const SELLER_PRODUCT_FAIL = "SELLER_PRODUCT_FAIL";

// update product
export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_FAIL = "UPDATE_PRODUCT_FAIL";
export const UPDATE_PRODUCT_RESET = "UPDATE_PRODUCT_RESET";

// product request --- admin
export const ADMIN_PRODUCT_REQUEST = "ADMIN_PRODUCT_REQUEST";
export const ADMIN_PRODUCT_SUCCESS = "ADMIN_PRODUCT_SUCCESS";
export const ADMIN_PRODUCT_FAIL = "ADMIN_PRODUCT_FAIL";

// delete product --- seller, admin
export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL";
export const DELETE_PRODUCT_RESET = "DELETE_PRODUCT_RESET";

// clear errors
export const CLEAR_ERRORS = "CLEAR_ERRORS";