export const ALL_SHOP_REQUEST = "ALL_SHOP_REQUEST";
export const ALL_SHOP_SUCCESS = "ALL_SHOP_SUCCESS";
export const ALL_SHOP_FAIL = "ALL_SHOP_FAIL";

export const SHOP_DETAILS_REQUEST = "SHOP_DETAILS_REQUEST";
export const SHOP_DETAILS_SUCCESS = "SHOP_DETAILS_SUCCESS";
export const SHOP_DETAILS_FAIL = "SHOP_DETAILS_FAIL";

export const ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST";
export const ALL_PRODUCT_SUCCESS = "ALL_PRODUCT_SUCCESS";
export const ALL_PRODUCT_FAIL = "ALL_PRODUCT_FAIL";


export const USER_LOGIN_REQUEST = "ALL_PRODUCT_REQUEST";
export const USER_LOGIN_SUCCESS = "ALL_PRODUCT_SUCCESS";
export const USER_LOGIN_FAIL = "ALL_PRODUCT_FAIL";

export const USER_REGISTER_REQUEST = "ALL_PRODUCT_REQUEST";
export const USER_REGISTER_SUCCESS = "ALL_PRODUCT_SUCCESS";
export const USER_REGISTER_FAIL = "ALL_PRODUCT_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";